apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep_cv
  namespace: jerinraj
  annotations:
    kubernetes.io/change-cause: "Original"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: nginx
      - name: c2
        image: redis
